package jp.sharakova.android.emoji;

public class EmojiUtils {
	
	public static String convertTag(String str){
		return str
		.replaceAll("<", "&lt;")
		.replaceAll(">", "&gt;")
		.replaceAll("%%i:1%%","<img src=\"e01\"/>")
		.replaceAll("%%i:2%%","<img src=\"e02\"/>")
		.replaceAll("%%i:3%%","<img src=\"e03\"/>")
		.replaceAll("%%i:4%%","<img src=\"e04\"/>")
		.replaceAll("%%i:5%%","<img src=\"e05\"/>")
		.replaceAll("%%i:6%%","<img src=\"e06\"/>")
		.replaceAll("%%i:7%%","<img src=\"e07\"/>")
		.replaceAll("%%i:8%%","<img src=\"e08\"/>")
		.replaceAll("%%i:9%%","<img src=\"e09\"/>")
		.replaceAll("%%i:10%%","<img src=\"e10\"/>")
		.replaceAll("%%i:11%%","<img src=\"e11\"/>")
		.replaceAll("%%i:12%%","<img src=\"e12\"/>")
		.replaceAll("%%i:13%%","<img src=\"e13\"/>")
		.replaceAll("%%i:14%%","<img src=\"e14\"/>")
		.replaceAll("%%i:15%%","<img src=\"e15\"/>")
		.replaceAll("%%i:16%%","<img src=\"e16\"/>")
		.replaceAll("%%i:17%%","<img src=\"e17\"/>")
		.replaceAll("%%i:18%%","<img src=\"e18\"/>")
		.replaceAll("%%i:19%%","<img src=\"e19\"/>")
		.replaceAll("%%i:20%%","<img src=\"e20\"/>")
		.replaceAll("%%i:21%%","<img src=\"e21\"/>")
		.replaceAll("%%i:22%%","<img src=\"e22\"/>")
		.replaceAll("%%i:23%%","<img src=\"e23\"/>")
		.replaceAll("%%i:24%%","<img src=\"e24\"/>")
		.replaceAll("%%i:25%%","<img src=\"e25\"/>")
		.replaceAll("%%i:26%%","<img src=\"e26\"/>")
		.replaceAll("%%i:27%%","<img src=\"e27\"/>")
		.replaceAll("%%i:28%%","<img src=\"e28\"/>")
		.replaceAll("%%i:29%%","<img src=\"e29\"/>")
		.replaceAll("%%i:30%%","<img src=\"e30\"/>")
		.replaceAll("%%i:31%%","<img src=\"e31\"/>")
		.replaceAll("%%i:32%%","<img src=\"e32\"/>")
		.replaceAll("%%i:33%%","<img src=\"e33\"/>")
		.replaceAll("%%i:34%%","<img src=\"e34\"/>")
		.replaceAll("%%i:35%%","<img src=\"e35\"/>")
		.replaceAll("%%i:36%%","<img src=\"e36\"/>")
		.replaceAll("%%i:37%%","<img src=\"e37\"/>")
		.replaceAll("%%i:38%%","<img src=\"e38\"/>")
		.replaceAll("%%i:39%%","<img src=\"e39\"/>")
		.replaceAll("%%i:40%%","<img src=\"e40\"/>")
		.replaceAll("%%i:41%%","<img src=\"e41\"/>")
		.replaceAll("%%i:42%%","<img src=\"e42\"/>")
		.replaceAll("%%i:43%%","<img src=\"e43\"/>")
		.replaceAll("%%i:44%%","<img src=\"e44\"/>")
		.replaceAll("%%i:45%%","<img src=\"e45\"/>")
		.replaceAll("%%i:46%%","<img src=\"e46\"/>")
		.replaceAll("%%i:47%%","<img src=\"e47\"/>")
		.replaceAll("%%i:48%%","<img src=\"e48\"/>")
		.replaceAll("%%i:49%%","<img src=\"e49\"/>")
		.replaceAll("%%i:50%%","<img src=\"e50\"/>")
		;
	}
}